### ISSUE TITLE
YOLOX-S

### ISSUE THREAD

**Issue by Zafoue** [cj-mills/barracuda-inference-yolox-demo#5]
Hello,

I have tested YOLOX-S within the project, using a custom ColorMap to map the COCO classes. I have also changed the test image for inference. However, it seems that it is not working.

Thank you.

**Comment by cj-mills** [comment]
Hi @Zafoue,

I can't be sure of the cause without more information. However, the pretrained models from the official YOLOX GitHub repository will not work with Barracuda. 

I provide baseline COCO models that work with Barracuda and a colormap for the COCO dataset in the following Hugging Face Hub repository:

- [yolox-coco-baseline-onnx](https://huggingface.co/cj-mills/yolox-coco-baseline-onnx/tree/main)

**Comment by Zafoue** [comment]
Hi @cj-mills 

I managed to get it to work on Jupyter .

Do you have a tutorial for creating a custom dataset?

**Comment by cj-mills** [comment]
Hi @Zafoue,

I [answered](https://github.com/cj-mills/christianjmills/issues/41#issuecomment-1864884424) your earlier post of this question. Please only ask a given question in a single location.
